import Link from "next/link"
import { Activity, ArrowUpRight, CircleGauge, ClipboardList, MapPinned, Package, RadioTower, Users } from "lucide-react"
import { count, desc, eq, gte, sql } from "drizzle-orm"
import { db, isDatabaseConfigured } from "@/db"
import { coverageAreas, coverageChecks, internetPlans, leads } from "@/db/schema"

type MetricProps = { label: string; value: number; detail: string; icon: typeof Users; tone: "orange" | "ink" | "lime" | "sky" }
const toneClasses = { orange: "bg-primary text-primary-foreground", ink: "bg-secondary text-secondary-foreground", lime: "bg-lime-100 text-lime-800", sky: "bg-sky-100 text-sky-800" }

function MetricCard({ label, value, detail, icon: Icon, tone }: MetricProps) { return <article className="rounded-[1.35rem] border border-border/70 bg-card p-5 shadow-[0_1px_0_rgba(27,35,43,.03)]"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-muted-foreground">{label}</p><p className="mt-3 text-3xl font-black tracking-tight">{value}</p></div><span className={`grid size-10 place-items-center rounded-2xl ${toneClasses[tone]}`}><Icon className="size-5" /></span></div><div className="mt-5 flex items-center justify-between"><p className="text-xs font-semibold text-muted-foreground">{detail}</p><div className="flex h-5 items-end gap-0.5" aria-hidden="true">{[6, 12, 9, 17, 13, 20].map((height, index) => <span key={index} className="w-1 rounded-full bg-primary/35" style={{ height }} />)}</div></div></article> }

export default async function AdminDashboard() {
  if (!isDatabaseConfigured) return <SetupState />
  const since = new Date(new Date().getFullYear(), new Date().getMonth(), 1)
  const [[leadCount], [checkCount], [planCount], [areaCount], recentLeads, statusRows] = await Promise.all([
    db.select({ value: count() }).from(leads).where(gte(leads.createdAt, since)),
    db.select({ value: count() }).from(coverageChecks).where(gte(coverageChecks.createdAt, since)),
    db.select({ value: count() }).from(internetPlans).where(eq(internetPlans.isActive, true)),
    db.select({ value: count() }).from(coverageAreas).where(eq(coverageAreas.status, "AVAILABLE")),
    db.select({ id: leads.id, name: leads.name, city: leads.city, status: leads.status, createdAt: leads.createdAt }).from(leads).orderBy(desc(leads.createdAt)).limit(6),
    db.select({ status: leads.status, value: count() }).from(leads).groupBy(leads.status),
  ])
  const statusCount = Object.fromEntries(statusRows.map((row) => [row.status, row.value])) as Record<string, number>
  const metrics: MetricProps[] = [
    { label: "Leads bulan ini", value: leadCount.value, detail: "Permintaan baru masuk", icon: Users, tone: "orange" },
    { label: "Coverage checks", value: checkCount.value, detail: "Pengecekan lokasi", icon: MapPinned, tone: "sky" },
    { label: "Paket aktif", value: planCount.value, detail: "Tayang di website", icon: Package, tone: "ink" },
    { label: "Area tersedia", value: areaCount.value, detail: "Coverage aktif", icon: RadioTower, tone: "lime" },
  ]
  const pipeline = [["Baru", statusCount.NEW ?? 0, "bg-primary"], ["Dihubungi", statusCount.CONTACTED ?? 0, "bg-amber-400"], ["Survey", statusCount.SURVEY ?? 0, "bg-sky-500"], ["Instalasi", statusCount.INSTALLATION ?? 0, "bg-lime-500"]]
  const maxPipeline = Math.max(1, ...pipeline.map(([, value]) => value as number))
  return <div className="mx-auto max-w-7xl pb-10"><header className="flex flex-wrap items-center justify-between gap-5"><div><p className="text-sm font-semibold text-primary">OPERATIONS OVERVIEW</p><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">Selamat datang kembali.</h1><p className="mt-2 text-sm text-muted-foreground">Pantau akuisisi pelanggan dan kesiapan jaringan dari satu tempat.</p></div><div className="flex items-center gap-3"><span className="hidden items-center gap-2 rounded-full border bg-card px-3 py-2 text-xs font-bold text-muted-foreground sm:inline-flex"><span className="size-2 rounded-full bg-lime-500" />Sistem operasional</span><Link href="/" target="_blank" className="inline-flex h-10 items-center gap-2 rounded-xl bg-secondary px-4 text-sm font-bold text-secondary-foreground">Lihat website <ArrowUpRight className="size-4" /></Link></div></header>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map((metric) => <MetricCard key={metric.label} {...metric} />)}</section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_.8fr]"><article className="overflow-hidden rounded-[1.5rem] bg-secondary p-6 text-secondary-foreground sm:p-7"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-bold tracking-[.16em] text-accent uppercase">Alur akuisisi</p><h2 className="mt-3 text-2xl font-black">Lead pipeline</h2><p className="mt-2 max-w-md text-sm leading-6 text-secondary-foreground/60">Fokuskan tindak lanjut pada calon pelanggan yang sudah menyelesaikan cek coverage.</p></div><span className="grid size-11 place-items-center rounded-2xl bg-secondary-foreground/10 text-accent"><Activity className="size-5" /></span></div><div className="mt-9 grid grid-cols-4 gap-4">{pipeline.map(([label, value, color]) => <div key={label as string}><p className="text-2xl font-black">{value as number}</p><p className="mt-1 text-xs text-secondary-foreground/55">{label as string}</p><div className="mt-4 flex h-24 items-end"><div className={`w-full rounded-t-xl ${color as string}`} style={{ height: `${Math.max(14, ((value as number) / maxPipeline) * 100)}%` }} /></div></div>)}</div><Link href="/admin/leads" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-accent hover:underline">Buka semua leads <ArrowUpRight className="size-4" /></Link></article>
      <article className="rounded-[1.5rem] border border-border/70 bg-card p-6 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-muted-foreground">Network readiness</p><h2 className="mt-1 text-xl font-black">Coverage aktif</h2></div><CircleGauge className="size-6 text-primary" /></div><div className="mt-7 grid place-items-center"><div className="grid size-36 place-items-center rounded-full border-[12px] border-primary/15 border-t-primary"><div className="text-center"><p className="text-3xl font-black">{areaCount.value}</p><p className="mt-1 text-xs font-semibold text-muted-foreground">area tersedia</p></div></div></div><div className="mt-7 rounded-xl bg-muted p-4"><p className="text-sm font-bold">Perbarui coverage secara berkala</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Data tepat membantu tim menghindari follow-up ke area yang belum siap.</p><Link href="/admin/coverage" className="mt-3 inline-flex text-xs font-bold text-primary hover:underline">Kelola coverage →</Link></div></article></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_.8fr]"><article className="rounded-[1.5rem] border border-border/70 bg-card p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold text-muted-foreground">Aktivitas terbaru</p><h2 className="mt-1 text-xl font-black">Lead masuk terbaru</h2></div><Link href="/admin/leads" className="text-sm font-bold text-primary hover:underline">Lihat semua</Link></div><div className="mt-5 divide-y divide-border/70">{recentLeads.length ? recentLeads.map((lead) => <div key={lead.id} className="flex items-center justify-between gap-4 py-4"><div className="flex min-w-0 items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-primary/10 text-xs font-black text-primary">{lead.name.slice(0, 2).toUpperCase()}</span><div className="min-w-0"><p className="truncate text-sm font-bold">{lead.name}</p><p className="truncate text-xs text-muted-foreground">{lead.city}</p></div></div><span className="rounded-full bg-muted px-2.5 py-1 text-[11px] font-bold text-muted-foreground">{lead.status}</span></div>) : <p className="py-8 text-sm text-muted-foreground">Belum ada lead masuk.</p>}</div></article>
      <article className="rounded-[1.5rem] border border-border/70 bg-card p-6"><ClipboardList className="size-5 text-primary" /><h2 className="mt-4 text-xl font-black">Quick actions</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Perbarui hal yang paling sering memengaruhi konversi.</p><div className="mt-5 grid gap-2">{[["Tambah paket", "/admin/plans"], ["Tambah coverage", "/admin/coverage"], ["Edit konten website", "/admin/website"]].map(([label, href]) => <Link key={href} href={href} className="flex items-center justify-between rounded-xl bg-muted px-4 py-3 text-sm font-bold transition hover:bg-primary hover:text-primary-foreground"><span>{label}</span><ArrowUpRight className="size-4" /></Link>)}</div></article></section>
  </div>
}

function SetupState() { return <section className="max-w-xl rounded-[1.5rem] border border-amber-200 bg-amber-50 p-7 text-amber-950"><p className="text-xs font-bold tracking-[.16em] uppercase">Setup diperlukan</p><h1 className="mt-2 text-2xl font-black">Database belum dikonfigurasi</h1><p className="mt-3 text-sm leading-6">Tambahkan DATABASE_URL, jalankan migrasi, lalu seed akun admin untuk membuka data operasional.</p></section> }
