import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import { ArrowRight, Check, Headphones, RadioTower, Router, Wrench } from "lucide-react"
import { CoverageChecker } from "@/components/coverage-checker"
import { PlanCard } from "@/components/plan-card"
import { SiteFooter } from "@/components/site-footer"
import { SiteHeader } from "@/components/site-header"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import { getHomeContent } from "@/lib/services/home-content"
import type { HomeSection } from "@/lib/home-content"
import { getPublicFaqs, getPublicPlans, getPublicSettings } from "@/lib/services/public"

export const metadata: Metadata = { title: "Internet Cepat untuk Rumah & Bisnis", description: "Internet WiFi cepat dan stabil untuk rumah dan bisnis. Cek coverage, bandingkan paket, dan daftar pemasangan online.", alternates: { canonical: "/" } }

export default async function Home() {
  const [plans, faqs, settings, home] = await Promise.all([getPublicPlans(), getPublicFaqs(), getPublicSettings(), getHomeContent()])
  const content = new Map(home.map((section) => [section.key, section]))
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }
  const renderSection = (section: HomeSection) => {
    const c = section.content
    if (!section.isVisible || section.key === "footer") return null
    if (section.key === "hero") return <section key={section.key} className="overflow-hidden bg-background"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 lg:grid-cols-[1.04fr_.96fr] lg:items-center lg:px-8 lg:py-20"><div><p className="text-sm font-black tracking-[.16em] text-primary uppercase">{c.eyebrow}</p><h1 className="mt-5 max-w-xl whitespace-pre-line text-5xl font-black tracking-[-.055em] sm:text-6xl lg:text-7xl">{c.heading}</h1><p className="mt-6 max-w-lg text-lg leading-8 text-muted-foreground">{c.body}</p><div className="mt-8 flex flex-wrap gap-5 text-sm font-semibold">{[c.benefitOne, c.benefitTwo, c.benefitThree].map((item) => <span key={item} className="flex items-center gap-2"><Check className="size-4 text-primary" />{item}</span>)}</div><div className="mt-9 flex flex-wrap gap-3"><Link className="inline-flex h-12 items-center gap-2 rounded-xl bg-primary px-5 font-bold text-primary-foreground" href={c.primaryCtaHref}>{c.primaryCtaLabel}<ArrowRight className="size-4" /></Link><Link className="inline-flex h-12 items-center rounded-xl border px-5 font-bold" href={c.secondaryCtaHref}>{c.secondaryCtaLabel}</Link></div></div><div className="relative min-h-95 overflow-hidden rounded-[2rem] bg-primary/10 sm:min-h-125"><Image src={c.imageSrc} alt={c.imageAlt} fill priority sizes="(max-width: 1024px) 100vw, 50vw" unoptimized={c.imageSrc.startsWith("http")} className="object-cover" /></div></div></section>
    if (section.key === "coverage") return <section key={section.key} id="coverage" className="bg-secondary px-5 py-12 text-secondary-foreground lg:px-8"><div className="mx-auto grid max-w-5xl gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-black tracking-[.16em] text-accent uppercase">{c.eyebrow}</p><h2 className="mt-3 text-3xl font-black">{c.heading}</h2></div><div className="rounded-2xl bg-background p-5 text-foreground sm:p-6"><CoverageChecker /></div></div></section>
    if (section.key === "use-cases") return <section key={section.key} className="bg-muted/60 py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="text-sm font-black tracking-[.16em] text-primary uppercase">{c.eyebrow}</p><div className="mt-5 grid gap-8 lg:grid-cols-2"><h2 className="text-3xl font-black sm:text-4xl">{c.heading}</h2><div className="grid grid-cols-2 gap-px bg-border">{[c.itemOne, c.itemTwo, c.itemThree, c.itemFour].map((item) => <div key={item} className="bg-muted p-6 font-bold">{item}</div>)}</div></div></div></section>
    if (section.key === "network") { const features = [[Router, c.featureOne], [RadioTower, c.featureTwo], [Wrench, c.featureThree], [Headphones, c.featureFour]] as const; return <section key={section.key} className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><div className="relative min-h-80 overflow-hidden rounded-[2rem]"><Image src={c.imageSrc} alt={c.imageAlt} fill sizes="(max-width: 1024px) 100vw, 50vw" unoptimized={c.imageSrc.startsWith("http")} className="object-cover" /></div><div><p className="text-sm font-black tracking-[.16em] text-primary uppercase">{c.eyebrow}</p><h2 className="mt-3 text-3xl font-black">{c.heading}</h2><div className="mt-7 grid gap-5 sm:grid-cols-2">{features.map(([Icon, label]) => <div key={label} className="border-t pt-4"><Icon className="size-5 text-primary" /><p className="mt-3 font-bold">{label}</p></div>)}</div></div></div></section> }
    if (section.key === "installation") { const steps = [c.stepOne, c.stepTwo, c.stepThree, c.stepFour, c.stepFive, c.stepSix]; return <section key={section.key} className="bg-secondary py-20 text-secondary-foreground"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="text-sm font-black tracking-[.16em] text-accent uppercase">{c.eyebrow}</p><h2 className="mt-3 text-3xl font-black">{c.heading}</h2><ol className="mt-10 grid gap-5 md:grid-cols-3 lg:grid-cols-6">{steps.map((item, index) => <li key={item} className="border-t-2 border-accent pt-4"><span className="text-sm font-black text-accent">0{index + 1}</span><p className="mt-3 font-bold">{item}</p></li>)}</ol></div></section> }
    if (section.key === "final-cta") return <section key={section.key} className="bg-primary px-5 py-20 text-primary-foreground lg:px-8"><div className="mx-auto max-w-4xl text-center"><p className="text-sm font-black tracking-[.16em] text-accent uppercase">{c.eyebrow}</p><h2 className="mt-4 text-4xl font-black sm:text-5xl">{c.heading}</h2><Link className="mt-8 inline-flex h-12 items-center rounded-xl bg-background px-5 font-bold text-foreground" href={c.ctaHref}>{c.ctaLabel}</Link></div></section>
    return null
  }

  return <><SiteHeader /><main id="main">{home.filter((section) => section.key !== "footer").map((section) => <div key={section.key}>{renderSection(section)}{section.key === "coverage" && <PlansSection plans={plans} settings={settings} />}{section.key === "network" && <FaqSection faqs={faqs} />}</div>)}</main><SiteFooter /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} /></>
}

function PlansSection({ plans, settings }: { plans: Awaited<ReturnType<typeof getPublicPlans>>; settings: Awaited<ReturnType<typeof getPublicSettings>> }) { return <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-black tracking-[.16em] text-primary uppercase">Paket internet</p><h2 className="mt-3 text-3xl font-black sm:text-4xl">Pilih kecepatan sesuai ritmemu.</h2></div><Link className="font-bold text-primary hover:underline" href="/paket-internet">Bandingkan semua paket →</Link></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{plans.map((plan) => <PlanCard key={plan.id} plan={plan} settings={settings} />)}</div></section> }

function FaqSection({ faqs }: { faqs: Awaited<ReturnType<typeof getPublicFaqs>> }) { return <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-black tracking-[.16em] text-primary uppercase">FAQ</p><h2 className="mt-3 text-3xl font-black">Jawaban sebelum terhubung.</h2></div><Accordion className="gap-3" multiple>{faqs.map((faq) => <AccordionItem className="rounded-2xl border border-border bg-card px-5" key={faq.id} value={faq.id}><AccordionTrigger className="py-5 text-left">{faq.question}</AccordionTrigger><AccordionContent className="leading-7 text-muted-foreground">{faq.answer}</AccordionContent></AccordionItem>)}</Accordion></div></section> }
