import Image from "next/image"
import Link from "next/link"
import { MessageCircle } from "lucide-react"
import { Separator } from "@/components/ui/separator"
import { getHomeContent } from "@/lib/services/home-content"
import { getPublicSettings } from "@/lib/services/public"
import { generateWhatsAppUrl } from "@/lib/whatsapp"

export async function SiteFooter() { const [site, home] = await Promise.all([getPublicSettings(), getHomeContent()]); const footer = home.find((section) => section.key === "footer")?.content; const links = [["Layanan", [["Paket Internet", "/paket-internet"], ["Internet Rumah", "/internet-rumah"], ["Internet Bisnis", "/internet-bisnis"], ["Cek Coverage", "/cek-coverage"]]], ["Bantuan", [["FAQ", "/faq"], ["Kontak", "/kontak"], ["Bantuan", "/bantuan"]]], ["Perusahaan", [["Tentang", "/tentang"], ["Kebijakan Privasi", "/kebijakan-privasi"], ["Syarat & Ketentuan", "/syarat-ketentuan"]]]] as const; return <footer className="border-t border-border/70 bg-background text-foreground"><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid gap-10 md:grid-cols-[1.5fr_repeat(3,1fr)]"><div><Link href="/" className="inline-flex"><Image src="/brand/juliant-logo-transparent.png" alt="JULIANT.NET — Internet Cepat" width={220} height={79} className="h-8 w-auto max-w-48 object-contain brightness-125 sm:h-9" /></Link><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">{footer?.footerCopy ?? site.footerCopy ?? "Internet WiFi cepat dan stabil untuk rumah dan bisnis."}</p><a className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-primary transition hover:text-primary/75" href={generateWhatsAppUrl(site.whatsappNumber, `Halo ${site.brandName}, saya ingin bertanya mengenai pemasangan internet.`)} target="_blank" rel="noreferrer"><MessageCircle className="size-4" />{footer?.contactLabel ?? "Chat WhatsApp"}</a></div>{links.map(([title, items]) => <div key={title}><h2 className="font-bold">{title}</h2><ul className="mt-4 space-y-3">{items.map(([label, href]) => <li key={href}><Link className="text-sm text-muted-foreground hover:text-primary" href={href}>{label}</Link></li>)}</ul></div>)}</div><Separator className="my-10 bg-border" /><p className="text-sm text-muted-foreground">© {new Date().getFullYear()} {site.companyName}. Semua hak dilindungi.</p></div></footer> }
