import { eq } from "drizzle-orm"
import { NextResponse } from "next/server"
import { db, isDatabaseConfigured } from "@/db"
import { coverageAreas, faqs, internetPlans, testimonials } from "@/db/schema"
import { requireAdmin } from "@/lib/auth"
import { writeAuditLog } from "@/lib/audit"
import { coverageSchema, faqSchema, planSchema, testimonialSchema } from "@/lib/validations/admin"
const error = (message: string, status: number) => NextResponse.json({ error: message }, { status })
export async function PATCH(request: Request, { params }: RouteContext<"/api/admin/[entity]/[id]">) { try { const user = await requireAdmin(["SUPER_ADMIN", "ADMIN", "EDITOR"]); if (!isDatabaseConfigured) return error("Database belum dikonfigurasi.", 503); const { entity, id } = await params; const body: unknown = await request.json(); if (entity === "plans") { const p = planSchema.safeParse(body); if (!p.success) return error(p.error.issues[0]?.message ?? "Data tidak valid.", 400); const x = p.data; await db.update(internetPlans).set({ ...x, price: String(x.price), promoPrice: x.promoPrice ? String(x.promoPrice) : null, promoStartAt: x.promoStartAt ? new Date(x.promoStartAt) : null, promoEndAt: x.promoEndAt ? new Date(x.promoEndAt) : null }).where(eq(internetPlans.id, id)); } else if (entity === "coverage") { const p = coverageSchema.safeParse(body); if (!p.success) return error(p.error.issues[0]?.message ?? "Data tidak valid.", 400); const x = p.data; await db.update(coverageAreas).set({ ...x, latitude: x.latitude ? String(x.latitude) : null, longitude: x.longitude ? String(x.longitude) : null }).where(eq(coverageAreas.id, id)); } else if (entity === "faqs") { const p = faqSchema.safeParse(body); if (!p.success) return error(p.error.issues[0]?.message ?? "Data tidak valid.", 400); await db.update(faqs).set(p.data).where(eq(faqs.id, id)); } else if (entity === "testimonials") { const p = testimonialSchema.safeParse(body); if (!p.success) return error(p.error.issues[0]?.message ?? "Data tidak valid.", 400); await db.update(testimonials).set(p.data).where(eq(testimonials.id, id)); } else return error("Resource tidak ditemukan.", 404); await writeAuditLog(user.id, "updated", entity, id); return NextResponse.json({ ok: true }) } catch (caught) { console.error("Admin update failed", caught); return error("Aksi tidak diizinkan.", 401) } }
export async function DELETE(_request: Request, { params }: RouteContext<"/api/admin/[entity]/[id]">) { try { const user = await requireAdmin(["SUPER_ADMIN", "ADMIN"]); if (!isDatabaseConfigured) return error("Database belum dikonfigurasi.", 503); const { entity, id } = await params; if (entity === "plans") await db.update(internetPlans).set({ isArchived: true, isActive: false }).where(eq(internetPlans.id, id)); else if (entity === "coverage") await db.delete(coverageAreas).where(eq(coverageAreas.id, id)); else if (entity === "faqs") await db.delete(faqs).where(eq(faqs.id, id)); else if (entity === "testimonials") await db.delete(testimonials).where(eq(testimonials.id, id)); else return error("Resource tidak ditemukan.", 404); await writeAuditLog(user.id, entity === "plans" ? "archived" : "deleted", entity, id); return NextResponse.json({ ok: true }) } catch { return error("Aksi tidak diizinkan.", 401) } }
