import { relations } from "drizzle-orm"
import { boolean, integer, index, jsonb, numeric, pgEnum, pgTable, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/pg-core"

export const userRoles = ["SUPER_ADMIN", "ADMIN", "EDITOR", "SALES"] as const
export const coverageStatuses = ["AVAILABLE", "COMING_SOON", "UNAVAILABLE"] as const
export const leadStatuses = ["NEW", "CONTACTED", "SURVEY", "INSTALLATION", "ACTIVE", "LOST"] as const
export const leadSources = ["HOMEPAGE", "COVERAGE_CHECKER", "PLAN_SELECTION", "REGISTRATION", "WHATSAPP", "CONTACT_FORM"] as const

const userRoleEnum = pgEnum("user_role", userRoles)
const coverageStatusEnum = pgEnum("coverage_status", coverageStatuses)
const leadStatusEnum = pgEnum("lead_status", leadStatuses)
const leadSourceEnum = pgEnum("lead_source", leadSources)
const propertyTypeEnum = pgEnum("property_type", ["RESIDENTIAL", "BUSINESS"])
const pageStatusEnum = pgEnum("page_status", ["DRAFT", "PUBLISHED"])

export const users = pgTable("user", {
  id: varchar("id", { length: 36 }).primaryKey(), name: varchar("name", { length: 120 }).notNull(), email: varchar("email", { length: 255 }).notNull().unique(), emailVerified: boolean("email_verified").default(false).notNull(), image: varchar("image", { length: 2048 }), role: userRoleEnum("role").default("ADMIN").notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(),
})
export const sessions = pgTable("session", { id: varchar("id", { length: 36 }).primaryKey(), expiresAt: timestamp("expires_at").notNull(), token: varchar("token", { length: 255 }).notNull().unique(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(), ipAddress: varchar("ip_address", { length: 64 }), userAgent: varchar("user_agent", { length: 512 }), userId: varchar("user_id", { length: 36 }).notNull().references(() => users.id, { onDelete: "cascade" }) }, (table) => [index("session_user_idx").on(table.userId)])
export const accounts = pgTable("account", { id: varchar("id", { length: 36 }).primaryKey(), accountId: varchar("account_id", { length: 255 }).notNull(), providerId: varchar("provider_id", { length: 255 }).notNull(), userId: varchar("user_id", { length: 36 }).notNull().references(() => users.id, { onDelete: "cascade" }), accessToken: text("access_token"), refreshToken: text("refresh_token"), idToken: text("id_token"), accessTokenExpiresAt: timestamp("access_token_expires_at"), refreshTokenExpiresAt: timestamp("refresh_token_expires_at"), scope: varchar("scope", { length: 500 }), password: varchar("password", { length: 255 }), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() }, (table) => [index("account_user_idx").on(table.userId)])
export const verifications = pgTable("verification", { id: varchar("id", { length: 36 }).primaryKey(), identifier: varchar("identifier", { length: 255 }).notNull(), value: text("value").notNull(), expiresAt: timestamp("expires_at").notNull(), createdAt: timestamp("created_at"), updatedAt: timestamp("updated_at") }, (table) => [index("verification_identifier_idx").on(table.identifier)])

export const internetPlans = pgTable("internet_plans", { id: varchar("id", { length: 36 }).primaryKey(), name: varchar("name", { length: 100 }).notNull(), slug: varchar("slug", { length: 120 }).notNull().unique(), speedMbps: integer("speed_mbps").notNull(), price: numeric("price", { precision: 12, scale: 2 }).notNull(), promoPrice: numeric("promo_price", { precision: 12, scale: 2 }), promoLabel: varchar("promo_label", { length: 120 }), promoStartAt: timestamp("promo_start_at"), promoEndAt: timestamp("promo_end_at"), description: text("description").notNull(), deviceMin: integer("device_min").notNull(), deviceMax: integer("device_max"), benefits: jsonb("benefits").$type<string[]>().notNull(), isPopular: boolean("is_popular").default(false).notNull(), isActive: boolean("is_active").default(true).notNull(), isArchived: boolean("is_archived").default(false).notNull(), sortOrder: integer("sort_order").default(0).notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() }, (table) => [index("plan_listing_idx").on(table.isActive, table.isArchived, table.sortOrder)])

export const coverageAreas = pgTable("coverage_areas", { id: varchar("id", { length: 36 }).primaryKey(), province: varchar("province", { length: 120 }).notNull(), city: varchar("city", { length: 120 }).notNull(), district: varchar("district", { length: 120 }).notNull(), postalCode: varchar("postal_code", { length: 12 }).notNull(), status: coverageStatusEnum("status").notNull(), latitude: numeric("latitude", { precision: 10, scale: 7 }), longitude: numeric("longitude", { precision: 10, scale: 7 }), notes: text("notes"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() }, (table) => [uniqueIndex("coverage_location_unique").on(table.province, table.city, table.district, table.postalCode), index("coverage_search_idx").on(table.city, table.district, table.status)])
export const coverageChecks = pgTable("coverage_checks", { id: varchar("id", { length: 36 }).primaryKey(), address: varchar("address", { length: 255 }).notNull(), province: varchar("province", { length: 120 }).notNull(), city: varchar("city", { length: 120 }).notNull(), district: varchar("district", { length: 120 }).notNull(), postalCode: varchar("postal_code", { length: 12 }).notNull(), propertyType: propertyTypeEnum("property_type").notNull(), resultStatus: coverageStatusEnum("result_status").notNull(), coverageAreaId: varchar("coverage_area_id", { length: 36 }).references(() => coverageAreas.id, { onDelete: "set null" }), createdAt: timestamp("created_at").defaultNow().notNull() }, (table) => [index("coverage_checks_created_idx").on(table.createdAt)])

export const leads = pgTable("leads", { id: varchar("id", { length: 36 }).primaryKey(), name: varchar("name", { length: 120 }).notNull(), phone: varchar("phone", { length: 32 }).notNull(), email: varchar("email", { length: 255 }), address: varchar("address", { length: 255 }).notNull(), province: varchar("province", { length: 120 }).notNull(), city: varchar("city", { length: 120 }).notNull(), district: varchar("district", { length: 120 }).notNull(), postalCode: varchar("postal_code", { length: 12 }).notNull(), propertyType: propertyTypeEnum("property_type").notNull(), planId: varchar("plan_id", { length: 36 }).references(() => internetPlans.id, { onDelete: "set null" }), coverageAreaId: varchar("coverage_area_id", { length: 36 }).references(() => coverageAreas.id, { onDelete: "set null" }), source: leadSourceEnum("source").notNull(), status: leadStatusEnum("status").default("NEW").notNull(), notes: text("notes"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() }, (table) => [index("lead_status_created_idx").on(table.status, table.createdAt), index("lead_plan_idx").on(table.planId)])

export const pages = pgTable("pages", { id: varchar("id", { length: 36 }).primaryKey(), slug: varchar("slug", { length: 150 }).notNull().unique(), title: varchar("title", { length: 180 }).notNull(), status: pageStatusEnum("status").default("DRAFT").notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() })
export const pageSections = pgTable("page_sections", { id: varchar("id", { length: 36 }).primaryKey(), pageId: varchar("page_id", { length: 36 }).notNull().references(() => pages.id, { onDelete: "cascade" }), sectionKey: varchar("section_key", { length: 80 }).notNull(), sectionType: varchar("section_type", { length: 80 }).notNull(), content: jsonb("content").$type<Record<string, string>>().notNull(), sortOrder: integer("sort_order").default(0).notNull(), isVisible: boolean("is_visible").default(true).notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() }, (table) => [uniqueIndex("page_section_key_unique").on(table.pageId, table.sectionKey)])
export const faqs = pgTable("faqs", { id: varchar("id", { length: 36 }).primaryKey(), question: varchar("question", { length: 255 }).notNull(), answer: text("answer").notNull(), sortOrder: integer("sort_order").default(0).notNull(), isPublished: boolean("is_published").default(true).notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() }, (table) => [index("faq_listing_idx").on(table.isPublished, table.sortOrder)])
export const mediaAssets = pgTable("media_assets", { id: varchar("id", { length: 36 }).primaryKey(), filename: varchar("filename", { length: 255 }).notNull(), key: varchar("storage_key", { length: 500 }).notNull().unique(), url: varchar("url", { length: 2048 }).notNull(), mimeType: varchar("mime_type", { length: 100 }).notNull(), size: integer("size").notNull(), width: integer("width"), height: integer("height"), altText: varchar("alt_text", { length: 255 }), createdAt: timestamp("created_at").defaultNow().notNull() })
export const testimonials = pgTable("testimonials", { id: varchar("id", { length: 36 }).primaryKey(), name: varchar("name", { length: 120 }).notNull(), location: varchar("location", { length: 160 }), quote: text("quote").notNull(), avatarId: varchar("avatar_id", { length: 36 }).references(() => mediaAssets.id, { onDelete: "set null" }), rating: integer("rating"), sortOrder: integer("sort_order").default(0).notNull(), isPublished: boolean("is_published").default(false).notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() })
export const seoMetadata = pgTable("seo_metadata", { id: varchar("id", { length: 36 }).primaryKey(), pageId: varchar("page_id", { length: 36 }).notNull().unique().references(() => pages.id, { onDelete: "cascade" }), metaTitle: varchar("meta_title", { length: 180 }), metaDescription: varchar("meta_description", { length: 320 }), canonicalUrl: varchar("canonical_url", { length: 2048 }), ogTitle: varchar("og_title", { length: 180 }), ogDescription: varchar("og_description", { length: 320 }), ogImageId: varchar("og_image_id", { length: 36 }).references(() => mediaAssets.id, { onDelete: "set null" }), noIndex: boolean("no_index").default(false).notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() })
export const siteSettings = pgTable("site_settings", { id: varchar("id", { length: 36 }).primaryKey(), companyName: varchar("company_name", { length: 160 }).notNull(), brandName: varchar("brand_name", { length: 160 }).notNull(), logoId: varchar("logo_id", { length: 36 }).references(() => mediaAssets.id, { onDelete: "set null" }), faviconId: varchar("favicon_id", { length: 36 }).references(() => mediaAssets.id, { onDelete: "set null" }), whatsappNumber: varchar("whatsapp_number", { length: 32 }).notNull(), phone: varchar("phone", { length: 32 }), email: varchar("email", { length: 255 }), businessAddress: text("business_address"), mapsUrl: varchar("maps_url", { length: 2048 }), operatingHours: varchar("operating_hours", { length: 255 }), instagram: varchar("instagram", { length: 2048 }), facebook: varchar("facebook", { length: 2048 }), tiktok: varchar("tiktok", { length: 2048 }), youtube: varchar("youtube", { length: 2048 }), defaultSeoTitle: varchar("default_seo_title", { length: 180 }).notNull(), defaultSeoDescription: varchar("default_seo_description", { length: 320 }).notNull(), defaultOgImageId: varchar("default_og_image_id", { length: 36 }).references(() => mediaAssets.id, { onDelete: "set null" }), footerCopy: text("footer_copy"), updatedAt: timestamp("updated_at").defaultNow().notNull() })
export const auditLogs = pgTable("audit_logs", { id: varchar("id", { length: 36 }).primaryKey(), userId: varchar("user_id", { length: 36 }).references(() => users.id, { onDelete: "set null" }), action: varchar("action", { length: 120 }).notNull(), entityType: varchar("entity_type", { length: 80 }).notNull(), entityId: varchar("entity_id", { length: 36 }), metadata: jsonb("metadata").$type<Record<string, unknown>>(), createdAt: timestamp("created_at").defaultNow().notNull() }, (table) => [index("audit_created_idx").on(table.createdAt)])

export const planRelations = relations(internetPlans, ({ many }) => ({ leads: many(leads) }))
export const leadRelations = relations(leads, ({ one }) => ({ plan: one(internetPlans, { fields: [leads.planId], references: [internetPlans.id] }), coverageArea: one(coverageAreas, { fields: [leads.coverageAreaId], references: [coverageAreas.id] }) }))
