import { asc, desc } from "drizzle-orm"
import { NextResponse } from "next/server"
import { db, isDatabaseConfigured } from "@/db"
import { coverageAreas, faqs, internetPlans, testimonials } from "@/db/schema"
import { requireAdmin } from "@/lib/auth"
import { writeAuditLog } from "@/lib/audit"
import { coverageSchema, faqSchema, planSchema, testimonialSchema } from "@/lib/validations/admin"

const error = (message: string, status: number) => NextResponse.json({ error: message }, { status })
export async function GET(_request: Request, { params }: RouteContext<"/api/admin/[entity]">) { try { await requireAdmin(); if (!isDatabaseConfigured) return NextResponse.json({ items: [] }); const { entity } = await params; if (entity === "plans") return NextResponse.json({ items: await db.select().from(internetPlans).orderBy(asc(internetPlans.sortOrder), asc(internetPlans.speedMbps)) }); if (entity === "coverage") return NextResponse.json({ items: await db.select().from(coverageAreas).orderBy(asc(coverageAreas.province), asc(coverageAreas.city), asc(coverageAreas.district)) }); if (entity === "faqs") return NextResponse.json({ items: await db.select().from(faqs).orderBy(asc(faqs.sortOrder)) }); if (entity === "testimonials") return NextResponse.json({ items: await db.select().from(testimonials).orderBy(asc(testimonials.sortOrder), desc(testimonials.createdAt)) }); return error("Resource tidak ditemukan.", 404) } catch { return error("Akses admin diperlukan.", 401) } }
export async function POST(request: Request, { params }: RouteContext<"/api/admin/[entity]">) { try { const user = await requireAdmin(["SUPER_ADMIN", "ADMIN", "EDITOR"]); if (!isDatabaseConfigured) return error("Database belum dikonfigurasi.", 503); const { entity } = await params; const body: unknown = await request.json(); const id = crypto.randomUUID(); if (entity === "plans") { const parsed = planSchema.safeParse(body); if (!parsed.success) return error(parsed.error.issues[0]?.message ?? "Data tidak valid.", 400); const x = parsed.data; await db.insert(internetPlans).values({ id, ...x, price: String(x.price), promoPrice: x.promoPrice ? String(x.promoPrice) : null, promoStartAt: x.promoStartAt ? new Date(x.promoStartAt) : null, promoEndAt: x.promoEndAt ? new Date(x.promoEndAt) : null }); } else if (entity === "coverage") { const parsed = coverageSchema.safeParse(body); if (!parsed.success) return error(parsed.error.issues[0]?.message ?? "Data tidak valid.", 400); const x = parsed.data; await db.insert(coverageAreas).values({ id, ...x, latitude: x.latitude ? String(x.latitude) : null, longitude: x.longitude ? String(x.longitude) : null }); } else if (entity === "faqs") { const parsed = faqSchema.safeParse(body); if (!parsed.success) return error(parsed.error.issues[0]?.message ?? "Data tidak valid.", 400); await db.insert(faqs).values({ id, ...parsed.data }); } else if (entity === "testimonials") { const parsed = testimonialSchema.safeParse(body); if (!parsed.success) return error(parsed.error.issues[0]?.message ?? "Data tidak valid.", 400); await db.insert(testimonials).values({ id, ...parsed.data }); } else return error("Resource tidak ditemukan.", 404); await writeAuditLog(user.id, "created", entity, id); return NextResponse.json({ id }, { status: 201 }) } catch (caught) { console.error("Admin create failed", caught); return error("Aksi tidak diizinkan atau data sudah ada.", 400) } }
