import { z } from "zod"

const optionalNumber = z.coerce.number().int().nonnegative().optional().or(z.literal(""))
export const planSchema = z.object({ name: z.string().trim().min(2).max(100), slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(120), speedMbps: z.coerce.number().int().positive(), price: z.coerce.number().nonnegative(), promoPrice: z.coerce.number().nonnegative().optional().nullable(), promoLabel: z.string().trim().max(120).optional().nullable(), promoStartAt: z.string().datetime().optional().nullable(), promoEndAt: z.string().datetime().optional().nullable(), description: z.string().trim().min(10).max(3000), deviceMin: z.coerce.number().int().positive(), deviceMax: z.coerce.number().int().positive().optional().nullable(), benefits: z.array(z.string().trim().min(1).max(120)).min(1).max(20), isPopular: z.boolean().default(false), isActive: z.boolean().default(true), sortOrder: z.coerce.number().int().nonnegative().default(0) })
export const coverageSchema = z.object({ province: z.string().trim().min(2).max(120), city: z.string().trim().min(2).max(120), district: z.string().trim().min(2).max(120), postalCode: z.string().trim().regex(/^\d{5}$/), status: z.enum(["AVAILABLE", "COMING_SOON", "UNAVAILABLE"]), latitude: z.coerce.number().min(-90).max(90).optional().nullable(), longitude: z.coerce.number().min(-180).max(180).optional().nullable(), notes: z.string().trim().max(2000).optional().nullable() })
export const faqSchema = z.object({ question: z.string().trim().min(5).max(255), answer: z.string().trim().min(5).max(5000), sortOrder: z.coerce.number().int().nonnegative().default(0), isPublished: z.boolean().default(true) })
export const testimonialSchema = z.object({ name: z.string().trim().min(2).max(120), location: z.string().trim().max(160).optional().nullable(), quote: z.string().trim().min(5).max(3000), rating: z.coerce.number().int().min(1).max(5).optional().nullable(), sortOrder: z.coerce.number().int().nonnegative().default(0), isPublished: z.boolean().default(false) })
export const leadStatusSchema = z.object({ status: z.enum(["NEW", "CONTACTED", "SURVEY", "INSTALLATION", "ACTIVE", "LOST"]), notes: z.string().trim().max(2000).optional().nullable() })
export const settingsSchema = z.object({ companyName: z.string().trim().min(2).max(160), brandName: z.string().trim().min(2).max(160), whatsappNumber: z.string().trim().regex(/^\d{10,16}$/), phone: z.string().trim().max(32).optional().nullable(), email: z.string().trim().email().max(255).optional().nullable(), businessAddress: z.string().trim().max(2000).optional().nullable(), mapsUrl: z.string().url().optional().nullable(), operatingHours: z.string().trim().max(255).optional().nullable(), instagram: z.string().url().optional().nullable(), facebook: z.string().url().optional().nullable(), tiktok: z.string().url().optional().nullable(), youtube: z.string().url().optional().nullable(), defaultSeoTitle: z.string().trim().min(5).max(180), defaultSeoDescription: z.string().trim().min(10).max(320), footerCopy: z.string().trim().max(2000).optional().nullable() })
